import { useEffect, useRef, useState } from 'react';
import { X, Link2, FileVideo, FileText, Upload, ArrowRight, LoaderCircle, FolderOpen, Check } from 'lucide-react';
import { api, post } from '../api';
type Mode = 'url' | 'mp4' | 'curate';
export default function CreateModal({ initial, onClose, onCreated }: { initial: Mode; onClose: () => void; onCreated: (id: string) => void }) {
  const [mode, setMode] = useState(initial);
  const [url, setUrl] = useState(''); const [title, setTitle] = useState(''); const [content, setContent] = useState('');
  const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [vault, setVault] = useState<{ path: string; title: string }[] | null>(null);
  const dialog = useRef<HTMLDivElement>(null); const previousFocus = useRef(document.activeElement as HTMLElement);
  useEffect(() => { dialog.current?.querySelector<HTMLButtonElement>('button')?.focus(); const current = previousFocus.current; return () => current?.focus(); }, []);
  async function chooseFile(value?: File) { if (!value) return; setError(''); if (mode === 'mp4') { if (!value.name.toLowerCase().endsWith('.mp4')) { setError('请选择 MP4 文件'); return; } setFile(value); } else { if (!value.name.toLowerCase().endsWith('.md')) { setError('请选择 Markdown 文件'); return; } if (value.size > 2_000_000) { setError('笔记不能超过 2 MB'); return; } setTitle(value.name.replace(/\.md$/i, '')); setContent(await value.text()); } }
  async function submit() { setBusy(true); setError(''); try { let job: { id: string }; if (mode === 'mp4') { if (!file) throw new Error('请先选择 MP4 文件'); const form = new FormData(); form.append('file', file); job = await api<{ id: string }>('/jobs/upload', { method: 'POST', body: form }); } else { job = await post<{ id: string }>('/jobs', { kind: mode, title: title || (mode === 'url' ? '视频笔记' : '整理笔记'), url, content }); } onCreated(job.id); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && !busy && onClose()}><div className="create-modal" role="dialog" aria-modal="true" aria-labelledby="create-title" ref={dialog} onKeyDown={e => { if (e.key === 'Escape' && !busy) onClose(); if (e.key === 'Tab') { const focusable = dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,[tabindex="0"]'); if (!focusable?.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } }}>
    <button className="icon-button modal-close" aria-label="关闭" onClick={onClose} disabled={busy}><X size={20}/></button>
    <span className="modal-emblem"><Upload size={25} strokeWidth={1.4}/></span><h2 id="create-title">拾起一份新知识</h2><p className="muted">把看过的、听过的，变成真正属于你的。</p>
    <div className="source-tabs">{([{ id: 'url', label: '视频链接', Icon: Link2 }, { id: 'mp4', label: '本地视频', Icon: FileVideo }, { id: 'curate', label: '整理笔记', Icon: FileText }] as const).map(({ id, label, Icon }) => <button disabled={busy} className={mode === id ? 'active' : ''} key={id} onClick={() => { setMode(id); setError(''); }}><Icon size={16}/>{label}</button>)}</div>
    {mode === 'url' && <div className="input-stack"><label htmlFor="video-url">视频网址</label><input id="video-url" type="url" autoComplete="off" value={url} onChange={e => setUrl(e.target.value)} placeholder="粘贴 YouTube 或哔哩哔哩视频链接"/><div className="source-badges"><span><i className="youtube-dot"/> YouTube</span><span><i className="bili-dot"/> bilibili</span><span>仅提取已有字幕</span></div><p className="helper">没有可获取字幕时会停止。已有自动字幕也可以使用。</p></div>}
    {mode === 'mp4' && <><label className="drop-zone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); chooseFile(e.dataTransfer.files[0]); }}><input type="file" accept=".mp4,video/mp4" aria-label="选择 MP4 视频" onChange={e => chooseFile(e.target.files?.[0])}/>{file ? <Check size={32}/> : <FileVideo size={36} strokeWidth={1.2}/>}<strong>{file?.name || '拖入视频，或点击选择'}</strong><span>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB` : 'MP4 · 最多 4 GB'}</span></label><p className="helper">提取声音后交给你配置的语音模型转写，长视频自动分段。</p></>}
    {mode === 'curate' && <div className="input-stack"><div className="import-actions"><label className="button subtle"><Upload size={15}/> 导入 Markdown<input type="file" accept=".md" aria-label="导入 Markdown 笔记" onChange={e => chooseFile(e.target.files?.[0])}/></label><button className="button subtle" onClick={async () => { try { setVault(await api('/vault/notes')); } catch (e) { setError((e as Error).message); } }}><FolderOpen size={15}/> 从仓库选择</button></div>{vault !== null && <select aria-label="选择仓库笔记" defaultValue="" onChange={async e => { if (!e.target.value) return; try { const note = await post<{ title: string; content: string }>('/vault/import', { path: e.target.value }); setTitle(note.title); setContent(note.content); setVault(null); } catch (e) { setError((e as Error).message); } }}><option value="">{vault.length ? '选择一篇笔记…' : '未找到笔记，请先在设置中连接仓库'}</option>{vault.map(n => <option value={n.path} key={n.path}>{n.path}</option>)}</select>}<input aria-label="笔记标题" value={title} onChange={e => setTitle(e.target.value)} placeholder="笔记标题"/><textarea aria-label="笔记内容" value={content} onChange={e => setContent(e.target.value)} placeholder="粘贴已有笔记，或导入 Markdown 文件…" rows={7}/><p className="helper">保留原始信息、图片引用与链接，整理后的笔记另存为新版本。</p></div>}
    {error && <div className="error-message" role="alert">{error}</div>}
    <div className="modal-footer"><span>长内容分段整理，完整保留细节</span><button className="button primary" disabled={busy || (mode === 'url' ? !url.trim() : mode === 'mp4' ? !file : !content.trim())} onClick={submit}>{busy ? <LoaderCircle className="spin" size={16}/> : null}{busy ? '正在提交…' : '开始拾知'}{!busy && <ArrowRight size={16}/>}</button></div>
  </div></div>;
}
