import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, BookOpen, FileText, FolderOpen, LoaderCircle, Plus, Search, Sparkles, Upload } from 'lucide-react';
import { api, post, type Note } from '../api';

export default function Library({ notes, onOpen, onGenerate, onChanged, notify }: {
  notes: Note[]; onOpen: (id: string, edit?: boolean) => void; onGenerate: () => void; onChanged: () => void; notify: (message: string) => void;
}) {
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all');
  const [repository, setRepository] = useState<{ path: string; available: boolean; pending: number } | null>(null);
  const [path, setPath] = useState(''); const [changing, setChanging] = useState(false); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const searchRef = useRef<HTMLInputElement>(null);
  useEffect(() => { api<{ path: string; available: boolean; pending: number }>('/repository').then(value => { setRepository(value); setPath(value.path); }).catch(e => setError(e.message)); }, []);
  useEffect(() => { const handler = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key === 'k') { e.preventDefault(); searchRef.current?.focus(); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  async function work(name: string, run: () => Promise<void>) { setBusy(name); setError(''); try { await run(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  const create = () => work('create', async () => { const note = await post<Note>('/notes', { title: '未命名笔记' }); onChanged(); onOpen(note.id, true); });
  const saveRepository = (target: string) => work('repository', async () => { const value = await api<{ path: string; available: boolean; pending: number }>('/repository', { method: 'PUT', body: JSON.stringify({ path: target }) }); setRepository(value); setPath(value.path); setChanging(false); onChanged(); notify('笔记已保存到所选仓库，原文件保留'); });
  const visible = notes.filter(note => (filter === 'all' || (filter === 'ai' ? note.kind !== 'manual' : note.kind === 'manual')) && (note.title + note.excerpt).toLowerCase().includes(search.toLowerCase()));
  return <div className="library page-enter">
    <div className="page-heading"><div><span className="section-kicker">理解，记录，慢慢连接</span><h1>我的笔记</h1><p>{notes.length} 篇笔记 · AI 帮你提炼，也留一页给自己的想法。</p></div><div className="library-actions"><button className="button secondary" disabled={!!busy} onClick={create}><Plus size={16}/>新建笔记</button><button className="button primary" onClick={onGenerate}><Sparkles size={16}/>AI 生成</button></div></div>
    <section className="repository-card"><FolderOpen size={22}/><div className="repository-info"><strong>本地笔记仓库 <span>Markdown 自动保存</span></strong><p title={repository?.path}>{repository?.path || '正在读取保存位置…'}</p>{repository && (!repository.available || repository.pending > 0) && <p className="repository-warning">{!repository.available ? '仓库暂不可用，请重新连接文件夹。' : `${repository.pending} 篇旧笔记等待保存，重新选择仓库即可补存。`}</p>}</div><div className="repository-actions">{window.glean && <button className="button subtle small" onClick={() => work('open', async () => { await window.glean!.openRepository(); })}>打开文件夹</button>}<button className="button secondary small" disabled={!!busy} onClick={() => work('choose', async () => { if (window.glean) { const chosen = await window.glean.chooseVault(); if (chosen) { setPath(chosen); setChanging(true); } } else setChanging(!changing); })}>更换仓库</button></div></section>
    {changing && <div className="repository-editor"><label>仓库文件夹<input aria-label="仓库文件夹" value={path} onChange={e => setPath(e.target.value)} placeholder="本地文件夹的绝对路径"/></label><p>全部现有笔记会复制到这里，以后的修改自动保存到这里；原文件保留，同名文件自动避让。</p><div><button className="button subtle small" onClick={() => setChanging(false)}>取消</button><button className="button primary small" disabled={!!busy || !path.trim()} onClick={() => saveRepository(path)}>{busy === 'repository' && <LoaderCircle size={14} className="spin"/>}使用此仓库</button></div></div>}
    {error && <div className="error-message" role="alert">{error}</div>}
    <div className="library-controls"><div className="filter-tabs">{[{ key: 'all', label: '全部笔记' }, { key: 'ai', label: 'AI 笔记' }, { key: 'manual', label: '手写 / 导入' }].map(item => <button key={item.key} className={filter === item.key ? 'active' : ''} onClick={() => setFilter(item.key)}>{item.label}</button>)}</div><label className="search-field"><Search size={16}/><input ref={searchRef} placeholder="搜索标题与摘要…" aria-label="搜索笔记" value={search} onChange={e => setSearch(e.target.value)}/><kbd>⌘ K</kbd></label><label className="button subtle small import-markdown"><Upload size={15}/>导入 Markdown<input type="file" accept=".md,text/markdown" disabled={!!busy} aria-label="直接导入 Markdown" onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (file) work('import', async () => { if (!file.name.toLowerCase().endsWith('.md') || file.size > 2_000_000) throw new Error('请选择不超过 2 MB 的 Markdown 文件'); const note = await post<Note>('/notes', { title: file.name.replace(/\.md$/i, '').slice(0, 160) || '导入笔记', content: await file.text() }); onChanged(); onOpen(note.id); }); }}/></label></div>
    {visible.length ? <div className="note-grid">{visible.map(note => <button key={note.id} className="note-card" onClick={() => onOpen(note.id)}><div><span className="note-file-icon"><FileText size={21}/></span><span className="tag">{note.kind === 'manual' ? '手写笔记' : note.kind === 'curate' ? 'AI 整理' : 'AI 生成'}</span></div><h2>{note.title}</h2><p>{note.excerpt}</p><div className="note-file-path" title={note.note_file}>{note.note_file ? note.note_file.split(/[\\/]/).pop() : '等待保存到仓库'}</div><footer><span>{new Date(note.updated_at).toLocaleDateString('zh-CN')} 更新 · {note.links} 个连接</span><ArrowUpRight size={17}/></footer></button>)}</div> : <div className="library-empty"><BookOpen size={42} strokeWidth={1}/><h2>{search || filter !== 'all' ? '没有找到匹配的笔记' : '从一份素材，或一页空白开始。'}</h2><p>AI 生成与手写笔记，都以 Markdown 文件保存在上方仓库。</p><div className="library-actions"><button className="button secondary" disabled={!!busy} onClick={create}><Plus size={16}/>写一篇笔记</button><button className="button primary" onClick={onGenerate}><Sparkles size={16}/>让 AI 帮我整理</button></div></div>}
  </div>;
}
