import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUp, BookOpen, Check, Copy, Download, ExternalLink, FileText, History, LoaderCircle, MessageCircle, Pencil, RefreshCw, Sparkles, X } from 'lucide-react';
import { api, download, post, type Note } from '../api';
import Markdown from './Markdown';
export default function NoteDetail({ id, onBack, onUpdated, onJobCreated, notify, onLink }: { id: string; onBack: () => void; onUpdated: () => void; onJobCreated: (id: string) => void; notify: (message: string) => void; onLink: (title: string) => void }) {
  const [note, setNote] = useState<Note | null>(null); const [tab, setTab] = useState('read'); const [draft, setDraft] = useState('');
  const [question, setQuestion] = useState(''); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [history, setHistory] = useState(false); const [chatVisible, setChatVisible] = useState(true);
  const bottom = useRef<HTMLDivElement>(null);
  useEffect(() => { setNote(null); setError(''); setTab('read'); api<Note>(`/notes/${id}`).then(n => { setNote(n); setDraft(n.content); }).catch(e => setError(e.message)); }, [id]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }, [note?.messages.length, busy]);
  async function action(name: string, work: () => Promise<void>) { setBusy(name); setError(''); try { await work(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  const ask = (text: string) => action('chat', async () => { const next = await post<Note>(`/notes/${id}/chat`, { message: text }); setNote(next); setDraft(next.content); setQuestion(''); onUpdated(); });
  return <div className="note-detail page-enter"><div className="note-toolbar"><button className="button text-button" onClick={onBack}><ArrowLeft size={17}/>所有笔记</button><div><button className="icon-button" title="版本历史" aria-label="版本历史" onClick={() => setHistory(!history)}><History size={18}/></button><button className="icon-button" title="导出 Markdown" aria-label="导出 Markdown" disabled={!note} onClick={() => note && download(note.title, note.content)}><Download size={18}/></button><button className="button secondary small" disabled={!!busy || !note} onClick={() => action('export', async () => { const result = await post<{ path: string }>(`/notes/${id}/export`); setNote(n => n && { ...n, vault_file: result.path }); notify('已写入 Obsidian 仓库'); })}>{busy === 'export' ? <LoaderCircle className="spin" size={15}/> : <ExternalLink size={15}/>}写入 Obsidian</button><button className={`icon-button ${chatVisible ? 'selected' : ''}`} title="知识对话" aria-label="切换知识对话" onClick={() => setChatVisible(!chatVisible)}><MessageCircle size={18}/></button></div></div>
    {error && <div className="error-message" role="alert">{error}</div>}
    {history && <div className="revision-panel"><div><strong>每一次生长，都有迹可循</strong><button className="icon-button" aria-label="关闭历史" onClick={() => setHistory(false)}><X size={16}/></button></div>{note?.revisions.length ? note.revisions.map(r => <div className="revision-row" key={r.id}><span>{({ chat_patch: '添加知识补丁', edit: '手动编辑', restore: '恢复版本', curate: 'AI 整理', original_import: '整理前的原始笔记' } as Record<string, string>)[r.reason] || r.reason}<small>{new Date(r.created_at).toLocaleString('zh-CN')}</small></span><button className="button subtle small" disabled={!!busy} onClick={() => action('restore', async () => { const next = await post<Note>(`/notes/${id}/restore/${r.id}`); setNote(next); setDraft(next.content); onUpdated(); notify('已恢复该次修改之前的内容'); })}>恢复修改前</button></div>) : <p className="muted">还没有修改记录。</p>}</div>}
    {!note ? <div className="loading-state"><LoaderCircle className="spin"/>正在展开笔记…</div> : <div className={`note-columns ${chatVisible ? '' : 'without-chat'}`}><section className="note-document"><header><div className="note-source"><span className="tag">{note.kind === 'txt' ? '字幕拾知' : note.kind === 'mp4' ? '声音拾知' : note.kind === 'url' ? '视频拾知' : '笔记整理'}</span><span>{new Date(note.created_at).toLocaleDateString('zh-CN')}</span></div><h1>{note.title}</h1><div className="note-source-line">来源：{note.source.startsWith('https://') ? <a href={note.source} target="_blank" rel="noreferrer">查看原视频 <ExternalLink size={12}/></a> : note.source}</div></header>
      <div className="document-tabs"><button className={tab === 'read' ? 'active' : ''} onClick={() => setTab('read')}><BookOpen size={15}/>笔记</button><button className={tab === 'transcript' ? 'active' : ''} onClick={() => setTab('transcript')}><FileText size={15}/>原始字幕</button><button className={tab === 'edit' ? 'active' : ''} disabled={busy === 'chat'} onClick={() => setTab('edit')}><Pencil size={14}/>编辑</button><button className="document-curate" disabled={!!busy} onClick={() => action('curate', async () => { const job = await post<{ id: string }>('/jobs', { kind: 'curate', note_id: id }); onJobCreated(job.id); notify('已加入整理队列，完成后重新打开此笔记即可查看'); })}><Sparkles size={14}/>重新整理</button></div>
      {tab === 'read' && <article className="markdown"><Markdown text={note.content.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '').replace(/^# [^\n]+\n/, '')} onLink={onLink}/></article>}
      {tab === 'transcript' && <div className="transcript"><div className="transcript-heading"><span>生成时使用的完整字幕</span>{note.transcript && <button className="button subtle small" onClick={() => download(note.title + '-原始字幕', note.transcript, 'txt')}><Download size={14}/>导出</button>}</div>{note.transcript ? <pre>{note.transcript}</pre> : <div className="empty-inline">这篇笔记来自 Markdown，没有原始字幕。聊天会使用笔记正文作为上下文。</div>}</div>}
      {tab === 'edit' && <div className="editor"><textarea aria-label="Markdown 编辑器" value={draft} onChange={e => setDraft(e.target.value)}/><div><span>支持 Obsidian Markdown 语法</span><button className="button primary small" disabled={!!busy || draft === note.content} onClick={() => action('save', async () => { const next = await api<Note>(`/notes/${id}`, { method: 'PUT', body: JSON.stringify({ content: draft, expected: note.content }) }); setNote(next); setDraft(next.content); onUpdated(); notify('笔记已保存'); })}><Check size={15}/>保存版本</button></div></div>}
      {note.vault_file && <button className="vault-saved" onClick={() => window.glean ? window.glean.openObsidian(note.vault_file) : notify(note.vault_file)}><Check size={13}/>已写入仓库 <ExternalLink size={13}/></button>}
    </section>{chatVisible && <aside className="chat-panel"><div className="chat-heading"><span className="chat-icon"><Sparkles size={19}/></span><div><h3>把知识，聊透。</h3><span>基于笔记{note.transcript ? '与原始字幕' : '正文'}</span></div><span className="status-dot"/></div><div className="chat-messages">{!note.messages.length && <div className="chat-welcome"><div className="chat-welcome-art"><MessageCircle size={33} strokeWidth={1}/><span>?</span></div><h4>好的问题，是理解的开始。</h4><p>追问概念，厘清联系。值得留下的解释，会成为笔记的一部分。</p><button onClick={() => ask('这篇笔记的核心概念是什么？请用通俗的语言讲清楚。')} disabled={!!busy || tab === 'edit'}>用通俗的话解释核心概念 <ArrowUp size={13}/></button><button onClick={() => ask('请根据原文梳理这些知识点之间的联系，不要增加原文没有的事实。')} disabled={!!busy || tab === 'edit'}>帮我串起知识点之间的联系 <ArrowUp size={13}/></button></div>}{note.messages.map(message => <div key={message.id} className={`chat-message ${message.role}`}><span className="message-author">{message.role === 'user' ? '你' : '拾知'}</span><div className="markdown"><Markdown text={message.content} onLink={onLink}/></div>{message.patch && <span className="patch-badge"><Sparkles size={12}/>{message.patch}</span>}</div>)}{busy === 'chat' && <div className="chat-thinking"><span/><span/><span/>正在梳理原文与笔记</div>}<div ref={bottom}/></div><form className="chat-composer" onSubmit={e => { e.preventDefault(); if (question.trim() && !busy && tab !== 'edit') ask(question.trim()); }}><textarea aria-label="向笔记提问" placeholder={tab === 'edit' ? '先保存编辑，再继续对话' : '有什么还想弄明白的？'} value={question} disabled={busy === 'chat' || tab === 'edit'} onChange={e => setQuestion(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); if (question.trim() && !busy && tab !== 'edit') ask(question.trim()); } }}/><div><span>Enter 发送 · Shift + Enter 换行</span><button aria-label="发送提问" disabled={!question.trim() || !!busy || tab === 'edit'}>{busy === 'chat' ? <LoaderCircle size={17} className="spin"/> : <ArrowUp size={18}/>}</button></div></form><p className="chat-footnote">有价值的解释自动补入笔记，支持版本恢复</p></aside>}</div>}
  </div>;
}
