import { useEffect, useState } from 'react';
import { Check, KeyRound, LoaderCircle, PlugZap, Save, SlidersHorizontal, Sparkles } from 'lucide-react';
import { api, post, type Settings } from '../api';
import SecretField from './SecretField';
export default function SettingsPage({ onSaved, notify }: { onSaved: () => void; notify: (message: string) => void }) {
  const [settings, setSettings] = useState<Settings | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [secretVersion, setSecretVersion] = useState(0);
  useEffect(() => { api<Settings>('/settings').then(setSettings).catch(e => setError(e.message)); }, []);
  const update = (key: keyof Settings, value: string | number | boolean | null) => setSettings(s => s ? { ...s, [key]: value } : s);
  async function save(test = false) { if (!settings) return; setBusy(test ? 'test' : 'save'); setError(''); try { const { has_api_key: _a, has_transcription_key: _b, ...value } = settings; const saved = await api<Settings>('/settings', { method: 'PUT', body: JSON.stringify(value) }); setSettings(saved); setSecretVersion(version => version + 1); onSaved(); if (test) await post('/settings/test'); notify(test ? '模型连接成功' : '设置已保存'); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  return <div className="settings-page page-enter"><div className="page-heading"><div><span className="section-kicker">按照你的习惯</span><h1>让拾知，更懂你。</h1><p>连接你的模型与知识库，剩下的交给好奇心。</p></div></div>{error && <div className="error-message" role="alert">{error}</div>}{!settings ? <p className="muted">正在读取设置…</p> : <>
    <section className="settings-section"><div className="settings-section-heading"><KeyRound size={20}/><div><h2>语言模型</h2><p>用于生成、整理笔记和与笔记对话</p></div><span className="mini-badge">Chat Completions 兼容接口</span></div><div className="form-grid"><label className="wide">Base URL<input value={settings.base_url} placeholder="https://api.example.com/v1" onChange={e => update('base_url', e.target.value)}/></label><label>模型名称<input value={settings.model} placeholder="填写服务商提供的模型 ID" onChange={e => update('model', e.target.value)}/></label><div className="form-field"><label htmlFor="api_key">API Key</label><SecretField key={`text-${secretVersion}`} name="api_key" label="语言模型 API Key" value={settings.api_key} saved={!!settings.has_api_key} placeholder="本地模型可以留空" onChange={value => update('api_key', value)} onError={setError}/></div></div></section>
    <section className="settings-section"><div className="settings-section-heading"><Sparkles size={20}/><div><h2>本地声音转字幕</h2><p>使用 Apple 芯片和 MLX Whisper，音频始终留在本机</p></div><span className="mini-badge">完全本地</span></div><div className="form-grid"><div className="form-field"><label>内置语音模型</label><div className="model-summary">Large V3 Turbo · 4-bit<span>已随应用安装 · 约 455 MB</span></div></div><label>主要语言<select value={settings.transcription_language} onChange={e => update('transcription_language', e.target.value)}><option value="auto">自动检测</option><option value="zh">普通话 / 中文</option><option value="en">英语</option></select></label><p className="field-note wide">无需下载模型，也无需配置语音 API。中文课程建议选择“普通话 / 中文”，专有名词较多或中英混合时选择“自动检测”。</p></div></section>
    <section className="settings-section"><div className="settings-section-heading"><SlidersHorizontal size={20}/><div><h2>学习偏好</h2><p>在完整记录与阅读体验之间找到适合你的节奏</p></div></div><div className="toggle-row"><div><strong>自动沉淀聊天补丁</strong><p>把有价值的解释补在对应原句旁，可在笔记历史中撤销</p></div><button className={`toggle ${settings.auto_patch ? 'on' : ''}`} role="switch" aria-checked={settings.auto_patch} aria-label="自动沉淀聊天补丁" onClick={() => update('auto_patch', !settings.auto_patch)}><span/></button></div><p className="field-note">生成时一次阅读全文，提炼成便于复习的精简笔记。原始字幕仍可随时查阅。</p></section>
    <div className="settings-footer"><p><Check size={14}/> 音频转写不会调用云端 API。若上方语言模型配置为云服务，生成笔记和对话时仍会发送字幕或笔记文本。</p><div><button className="button secondary" disabled={!!busy} onClick={() => save(true)}>{busy === 'test' ? <LoaderCircle size={16} className="spin"/> : <PlugZap size={16}/>}保存并测试</button><button className="button primary" disabled={!!busy} onClick={() => save()}>{busy === 'save' ? <LoaderCircle size={16} className="spin"/> : <Save size={16}/>}保存设置</button></div></div>
  </>}</div>;
}
