import { useEffect, useState } from 'react';
import { ArrowUpRight, Check, FolderOpen, KeyRound, LoaderCircle, PlugZap, Save, SlidersHorizontal, Sparkles } from 'lucide-react';
import { api, post, type Settings } from '../api';
export default function SettingsPage({ onSaved, notify }: { onSaved: () => void; notify: (message: string) => void }) {
  const [settings, setSettings] = useState<Settings | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  useEffect(() => { api<Settings>('/settings').then(setSettings).catch(e => setError(e.message)); }, []);
  const update = (key: keyof Settings, value: string | number | boolean | null) => setSettings(s => s ? { ...s, [key]: value } : s);
  async function save(test = false) { if (!settings) return; setBusy(test ? 'test' : 'save'); setError(''); try { const { has_api_key: _a, has_transcription_key: _b, ...value } = settings; const saved = await api<Settings>('/settings', { method: 'PUT', body: JSON.stringify(value) }); setSettings(saved); onSaved(); if (test) await post('/settings/test'); notify(test ? '模型连接成功' : '设置已保存'); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  return <div className="settings-page page-enter"><div className="page-heading"><div><span className="section-kicker">按照你的习惯</span><h1>让拾知，更懂你。</h1><p>连接你的模型与知识库，剩下的交给好奇心。</p></div></div>{error && <div className="error-message" role="alert">{error}</div>}{!settings ? <p className="muted">正在读取设置…</p> : <>
    <section className="settings-section"><div className="settings-section-heading"><KeyRound size={20}/><div><h2>语言模型</h2><p>用于生成、整理笔记和与笔记对话</p></div><span className="mini-badge">Chat Completions 兼容接口</span></div><div className="form-grid"><label className="wide">Base URL<input value={settings.base_url} placeholder="https://api.example.com/v1" onChange={e => update('base_url', e.target.value)}/></label><label>模型名称<input value={settings.model} placeholder="填写服务商提供的模型 ID" onChange={e => update('model', e.target.value)}/></label><label>API Key<div className="secret-field"><input type="password" autoComplete="off" value={settings.api_key || ''} placeholder={settings.has_api_key ? '已保存，留空保留原密钥' : '本地模型可以留空'} onChange={e => update('api_key', e.target.value)}/>{settings.has_api_key && <button onClick={() => update('api_key', null)} title="清除已保存密钥" aria-label="清除语言模型密钥">清除</button>}</div></label></div></section>
    <section className="settings-section"><div className="settings-section-heading"><Sparkles size={20}/><div><h2>声音转字幕</h2><p>仅在导入本地 MP4 时使用，支持 Whisper 兼容接口</p></div></div><div className="form-grid"><label className="wide">语音服务 Base URL<input value={settings.transcription_base_url} placeholder="留空使用上方地址" onChange={e => update('transcription_base_url', e.target.value)}/></label><label>语音模型<input value={settings.transcription_model} onChange={e => update('transcription_model', e.target.value)}/></label><label>语音服务 API Key<div className="secret-field"><input type="password" autoComplete="off" value={settings.transcription_key || ''} placeholder={settings.has_transcription_key ? '已保存，留空保留原密钥' : '留空使用上方密钥'} onChange={e => update('transcription_key', e.target.value)}/>{settings.has_transcription_key && <button onClick={() => update('transcription_key', null)}>清除</button>}</div></label></div></section>
    <section className="settings-section"><div className="settings-section-heading"><FolderOpen size={20}/><div><h2>Obsidian 仓库</h2><p>把生成的笔记送回你的知识库</p></div></div><div className="form-grid"><label className="wide">仓库位置<div className="input-action"><input value={settings.vault_path} placeholder="选择你的 Obsidian 仓库文件夹" onChange={e => update('vault_path', e.target.value)}/><button className="button secondary" onClick={async () => { if (!window.glean) { notify('浏览器预览请直接填写绝对路径；桌面版支持文件夹选择'); return; } const path = await window.glean.chooseVault(); if (path) update('vault_path', path); }}><FolderOpen size={15}/>选择文件夹</button></div></label><label>笔记保存文件夹<input value={settings.notes_folder} onChange={e => update('notes_folder', e.target.value)}/></label><p className="field-note">写入仓库时自动避开同名文件，每个版本都可以独立保留。</p></div></section>
    <section className="settings-section"><div className="settings-section-heading"><SlidersHorizontal size={20}/><div><h2>学习偏好</h2><p>在完整记录与阅读体验之间找到适合你的节奏</p></div></div><div className="toggle-row"><div><strong>自动沉淀聊天补丁</strong><p>把有价值的解释补在对应原句旁，可在笔记历史中撤销</p></div><button className={`toggle ${settings.auto_patch ? 'on' : ''}`} role="switch" aria-checked={settings.auto_patch} aria-label="自动沉淀聊天补丁" onClick={() => update('auto_patch', !settings.auto_patch)}><span/></button></div><div className="form-grid"><label>每段素材长度<select value={settings.chunk_chars} onChange={e => update('chunk_chars', Number(e.target.value))}><option value={4000}>4,000 字符 · 小上下文模型</option><option value={8000}>8,000 字符 · 更细致</option><option value={12000}>12,000 字符 · 均衡</option><option value={20000}>20,000 字符 · 大上下文模型</option></select></label><label>优先字幕语言<input value={settings.subtitle_languages} onChange={e => update('subtitle_languages', e.target.value)}/></label></div></section>
    <div className="settings-footer"><p><Check size={14}/> 笔记与字幕留在本机；处理时素材会发送到你配置的模型。密钥保存在仅当前用户可读的本地文件。</p><div><button className="button secondary" disabled={!!busy} onClick={() => save(true)}>{busy === 'test' ? <LoaderCircle size={16} className="spin"/> : <PlugZap size={16}/>}保存并测试</button><button className="button primary" disabled={!!busy} onClick={() => save()}>{busy === 'save' ? <LoaderCircle size={16} className="spin"/> : <Save size={16}/>}保存设置</button></div></div>
  </>}</div>;
}
